#spring:
#  redis:
#    cluster:
#      #设置key的生存时间，当key过期时，它会被自动删除；
#      expire-seconds: 120
#      #设置命令的执行时间，如果超过这个时间，则报错;
#      command-timeout: 5000
#      #设置redis集群的节点信息，其中namenode为域名解析，通过解析域名来获取相应的地址;
#      nodes: 10.3.1.5:9801,10.3.1.5:9802,10.3.1.5:9803,10.3.1.5:9804,10.3.1.5:9805,10.3.1.5:9806

server:
  port: 8083


spring:
  redis:
    #    host: 10.3.1.5
    #    port: 9801
#    password: abc123
    # Redis 默认数据库设置
    database: 0
    ssl: false
    timeout: 1000
    # Redis Cluster集群节点配置
    cluster:
      # Redis 集群地址信息
      nodes:
#        - 127.0.0.1:7000
#        - 127.0.0.1:7001
#        - 127.0.0.1:7002
#        - 127.0.0.1:7003
#        - 127.0.0.1:7004
#        - 127.0.0.1:7005
        - 139.155.73.4:6000
        - 139.155.73.4:6001
        - 139.155.73.4:6002
        - 139.155.73.4:6003
        - 139.155.73.4:6004
        - 139.155.73.4:6005
      #设置key的生存时间，当key过期时，它会被自动删除；
      expire-seconds: 120
      #设置命令的执行时间，如果超过这个时间，则报错;
      command-timeout: 1000
      # 获取失败 最大重定向次数
      max-redirects: 3
#    #如果用以前的jedis，可以把下面的lettuce换成jedis即可
    lettuce:
      pool:
        # 连接池最大连接数默认值为8
        max-active: 100
        # 连接池最大阻塞时间（使用负值表示没有限制）默认值为-1
        max-wait: -1
        # 连接池中最大空闲连接数默认值为8
        max-idle: 100
        # 连接池中的最小空闲连接数，默认值为0
        min-idle: 10




